# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "FSPRING-RMK-BLE"
product_name = "FSPRING-RMK-BLE"
vendor_id = 0xde17
product_id = 0xf516
manufacturer = "DEEMEN17"
chip = "nrf52840"
# board = "nice!nano_v2"

[matrix]
# Input and output pins are mandatory
col_pins = ["P0_13", "P0_14", "P0_15", "P0_16", "P1_02"]
row_pins = ["P1_11", "P1_12", "P1_13", "P1_14", "P1_15", "P0_03", "P0_17", "P0_21", "P0_20", "P0_23", "P0_22", "P1_00", "P0_24", "P0_25"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 5
cols = 14
layers = 2

matrix_map = """
(0,0) (1,0) (2,0) (3,0) (4,0) (5,0) (6,0) (6,4)     (7,0) (8,0) (9,0) (10,0) (11,0) (12,0)        (13,0) 
(0,1) (1,1) (2,1) (3,1) (4,1) (5,1) (6,1)           (7,1) (8,1) (9,1) (10,1) (11,1) (12,1) (12,4) (13,1) 
(0,2) (1,2) (2,2) (3,2) (4,2) (5,2) (6,2)           (7,2) (8,2) (9,2) (10,2) (11,2) (12,2)        (13,2) 
      (1,3) (2,3) (3,3) (4,3) (5,3) (6,3)           (7,3) (8,3) (9,3) (10,3) (11,3) (12,3)        (13,3) 
      (1,4) (2,4)       (4,4) (5,4)                       (8,4)       (10,4) (11,4) (12,4)        (13,4) 
"""

[[layer]]
name = "0"
keys = """
Home  grv   1     2     3     4     5     6         7     8     9     0     mins  eql         bspc
pgup  Tab   Q     W     E     R     T               Y     U     I     O     P     lbrc  rbrc  bsls
pgdn  caps  A     S     D     F     G               H     J     K     L     scln  quot        ent
      lsft  Z     X     C     V     B               B     N     M     comm  Dot   slsh        rsft
      lctl  lwin        l_alt spc                   spc               r_alt       MO(1)       rctl
"""

[[layer]]
name = "1"
keys = """
_     _     F1    F2    F3    F4    F5    F6        F7    F8    F9    F10   F11   F12         del
_     _     User0 User1 User2 _     _               _     _     _     _     _     _     _     _
_     _     User3 User4 User5 User6 _               _     _     _     _     _     _           _
      _     _     _     _     _     Bootloader      _     _     _     _     _     _           _
      _     _           _     _                     _                 _           _           _ 

"""

# Ble configuration
# To use the default configuration, ignore this section completely
[ble]
# Whether to enable BLE feature
enabled = true
# nRF52840's saadc pin for reading battery level, you can use a pin number or "vddh"
battery_adc_pin = "vddh"
# The voltage divider setting for saadc. This setting should be ignored when using "vddh" as the adc pin.
# For example, nice!nano has 806 + 2M resistors. The saadc measures voltage on the 2M resistor, so the two values should be set to 2000 and 2806
adc_divider_measured = 2000
adc_divider_total = 2806
# Set the BLE tx power; higher means better signal but more power consumption. For nRF52840 the maximum tx power is 8.
default_tx_power = 8
# Whether to enable 2M PHY, defaults to true.
# use_2m_phy = true
# [Deprecated] Pin that reads battery's charging state, `low-active` means the battery is charging when `charge_state.pin` is low
# charge_state = { pin = "PIN_1", low_active = true }
# [Deprecated] Output LED pin that blinks when the battery is low
# charge_led= { pin = "PIN_2", low_active = true }